version: '3.1'

services:

  wordpress:
    image: wordpress
    #restart: always
    volumes:
    - "./wp-content/themes:/var/www/html/wp-content/themes"
    - "./wp-content/plugins:/var/www/html/wp-content/plugins"
    ports:
    - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: example

  mysql:
    image: mysql:5.7
    #restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

    volumes:
    - wordpress-mysql-data:/var/lib/mysql

volumes:
  wordpress-mysql-data:
    driver: local